# version: '3.8'

# services:
#   api:
#     build: .
#     ports:
#       - "3000:3000"
#     env_file:
#       .env
#     depends_on:
#       - mongo
#     volumes:
#       - .:/app
#       - /app/node_modules

#   mongo:
#     image: mongo:latest
#     ports:
#       - "27018:27017"
#     volumes:
#       - mongo-data:/data/db

# volumes:
#   mongo-data:


version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  backend:
    build: .
    container_name: api
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - app-network


volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
